version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    open-pull-requests-limit: 3
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[SDK PHP]"
  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[SDK PHP]"
